services:
  - type: web
    name: medreel-backend
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY_1
        sync: false
      - key: GROQ_API_KEY_2
        sync: false
      - key: GROQ_API_KEY_3
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0
    healthCheckPath: /api/health
